
name: Build_and_run_unit_tests

on:
  push:
    branches: [ "develop" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Unit Tests
      run: dotnet test HouseRentingSystem.UnitTests/HouseRentingSystem.UnitTests.cproj --no-build --verbosity normal
